baseurl: "/"
languageCode: "en-us"
title: "Chandler Justice"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Posts
      url: "posts/"
params:
  description: "Chandler Justice's Personal Website."
  footer: "&copy; [Chandler Justice](https://chandlerjustice.com/) 2023 -- {Year}"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
